pipeline:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: 
        - linux/amd64
        - linux/arm/v8
      repo:
        from_secret: TARGET_REPOSITORY
      registry:
        from_secret: REGISTRY_HOST
      tags: latest
      username: 
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASSWORD
    when:
      event: push
      branch: main

  depl:
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: DEPLOYMENT_SERVER_HOST
      username:
        from_secret: DEPLOYMENT_SERVER_USER
      key:
        from_secret: DEPLOYMENT_SERVER_KEY
      port: 22
      script:
        from_secret: PROD_DEPLOYMENT_NAME
    when:
      event: push
      branch: main
